### ISSUE TITLE
Searching with non-capitals

### ISSUE THREAD

**Issue by Vasago** [Takenbacon/wowarmory#1]
There is an issue that causing names like "bob" not search right result as "Bob" - With capital letter it works but not with all small letters.

**Comment by Takenbacon** [comment]
I can't seem to reproduce this one, so let's say if you typed in "bob" it would return no results, but if you typed in "Bob" it would display the character?

**Comment by Vasago** [comment]
Yes

**Comment by Takenbacon** [comment]
Can you give me an exact example of what you were doing? Because I'm still unable to reproduce this. I've also heard of certain OS's acting differently to case-sensitive queries, can you tell me what OS the website is being ran from (Windows, Uinx, ect.)?

**Comment by Vasago** [comment]
Os Linux Ubuntu 64bit server edition:
When I type "bob" it shows:
No Search Results
Your search did not produce any results. To ensure that you're searching by parameters allowed by the Armory, make sure to:
- Only search for the categories currently in the Armory: items, characters, arena teams, guilds, and factions.
- Search by name only.

When I type Bob - it shows charcter Bob normally.

**Comment by Takenbacon** [comment]
Just curious, but if you typed in let's say BoB does it still work? Just checking what all i have to format in order to fix this.

**Comment by Vasago** [comment]
BoB does not work either ...

**Comment by Takenbacon** [comment]
Try it now, based off of what you told me this should solve it.
