### ISSUE TITLE
Invalid Query on logout

### ISSUE THREAD

**Issue by LeGuybrush** [Takenbacon/wowarmory#5]
`[1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1`

Pretty vague error, but occurs on player log out, crashing the server. Potential issue in patch -> player.cpp?

Occurs on https://github.com/TrinityCore/TrinityCore/commit/aad8c12a86f2

**Comment by LeGuybrush** [comment]
Narrowed it down. Crash occurs on boss kills (which triggers the type 3 feed log entry).

`if (creature->GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_INSTANCE_BIND)
{
((InstanceMap*)instanceMap)->PermBindAllPlayers(creditedPlayer);
creditedPlayer->CreateWowarmoryFeed(3, creature->GetCreatureTemplate()->Entry, 0, 0);
}`

**Comment by Takenbacon** [comment]
Most likely has something to do when i tweaked the query string builder.

https://github.com/Takenbacon/wowarmory/commit/0a32529b0e698475daf6eb56519456f475d6a1cf#L0R174

It's interesting how it's not giving the actual query that caused the error, don't believe I've ever seen that before. Try launching the worldserver from a bat file or command line, it might allow the actual query that caused the fault to display in the console (like it usually does).

**Comment by LeGuybrush** [comment]
@Takenbacon I got the error on console. I tried to get a more specific query but it never gives me one. Just the empty statement following VALUES.

I ran GDB and got some information, but unfortunately it doesn't yield anything more useful.

http://pastebin.com/hrJEZxLe

Btw thanks for getting back to me. I was worried you had disappeared :)

**Comment by Takenbacon** [comment]
Makes sense now, it was giving no query values because there was none. I forgot to add a check to make sure that there was actually data that needed to be saved, else m_wowarmory would be empty and cause a bad query.

**Comment by LeGuybrush** [comment]
@Takenbacon, I attributed this with another issue with the character sheet, specifically that it doesn't find the character, even after it's been logged into and out of, and entries made in the armory tables. Should this be corrected as well, or is this a separate issue?

**Comment by Takenbacon** [comment]
If it doesn't show the character even after the data has been saved, make sure you change the max gm level setting in the armory config, chances are it's probably blocking it from being viewed (the setting probably needs to be disabled by default, since several people have mentioned this). You can also usually tell by enabling debug then going to http://xxxx.com/armory/_cache/debug/

**Comment by LeGuybrush** [comment]
No homo. I love you.

**Comment by Takenbacon** [comment]
@flashadvocate No problem :+1:.

Also, I'm not really inactive, it's just i have other projects I'm working on and this armory needs so much work it's sad. I'll still continue to support it and make bug fixes when i can. I have a lot of free time coming up so i might do some more work, including adding APC cache support.
