### ISSUE TITLE
Player search query case sensitive

### ISSUE THREAD

**Issue by LeGuybrush** [Takenbacon/wowarmory#7]
This isn't a major issue, but something to note at any rate. When searching specifically for a character named "player", the search query "player" yields no results, whereas "Player" does.

This is a duplicate issue of #1, but apparently the fix did not solve the problem.

**Comment by LeGuybrush** [comment]
Fixed. class.search.php:664

``` php
$current_realm = $db->select("SELECT `guid`, `name`, `class` AS `classId`, `gender` AS `genderId`, `race` AS `raceId`, `level`, `account` FROM `characters` WHERE `name` = '%s'", $this->searchQuery);
```

should be

``` php
$current_realm = $db->select("SELECT `guid`, `name`, `class` AS `classId`, `gender` AS `genderId`, `race` AS `raceId`, `level`, `account` FROM `characters` WHERE `name` = '%s'", $search);
```

**Comment by Takenbacon** [comment]
Good catch, i guess i forgot that part as well when i did that change. I still to this day don't fully understand what causes that to happen on only certain setups. I'll just update the file via git.
